pr: none
trigger:
  - main
schedules:
  - cron: '0 0-5 * * 1-5' #Thanks crontab.guru
    displayName: Run renovate bot Monday through Friday every hour from 00:00 till 5:00.
    branches:
      include:
        - main
stages:
  - stage: Run
    jobs:
      - job: run_renovate
        displayName: 'Run Renovate'
        variables:
          - group: renovate
        steps:
          - task: NodeTool@0
            inputs:
              versionSource: 'spec'
              versionSpec: 22.x
              checkLatest: true
          - task: PowerShell@2
            displayName: 'Run Renovate'
            env: #Inject secret as secrets don't go into env by themselves.
              RENOVATE_CONFIG_FILE: './renovate-config.js' #needed when you name config file something else than config.js
              GITHUB_COM_TOKEN: $(GITHUB_TOKEN) #Insert github PAT here to see changelogs in PRs
              RENOVATE_TOKEN: $(RENOVATE_TOKEN)
            inputs:
              targetType: 'inline'
              script: |
                npm i
                npx renovate